pattern=settings/pattern.txt
out=results/hits.txt
checkpoint=checkpoints/hits.txt.checkpoint
serverJar=lib/minecraft_server.1.21.11.jar
serverDir=mc-lava-verifier-clean
threshold=1.0
rotate=true
type=floor
